networks:
  mamikos-network:
    name: mamikos-network
    external: true

services:
  nginx:
    image: nginx:alpine
    container_name: reverse-proxy-nginx
    restart: always
    volumes:
      - ./reverse-proxy-default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 9001:8080
    network_mode: host
