apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['kube-prometheus-stack-prometheus-node-exporter.monitoring.svc.cluster.local:9100']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-prometheus-stack-kube-state-metrics.monitoring.svc.cluster.local:8080']
      - job_name: 'alertmanager'
        static_configs:
          - targets: ['kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093']
      - job_name: 'grafana'
        metrics_path: /metrics
        static_configs:
          - targets: ['kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000']

