apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vuejs-app-hpa
  namespace: mamikos-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vuejs-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50