apiVersion: v1
kind: Pod
metadata:
  name: cpu-load-generator
  namespace: mamikos-devops
spec:
  containers:
  - name: cpu-load-generator
    image: polinux/stress
    resources:
      limits:
        cpu: "1"
    command: ["stress"]
    args: ["--cpu", "2", "--timeout", "30"]