name: deploy vue app into minikube cluster

on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Step 1: Checkout code
  checkout:
    runs-on: self-hosted
    name: Checkout Code
    steps:
    - uses: actions/checkout@v2
  
  # Step 2: Build and push Docker image to GHCR
  build_and_push:
    runs-on: self-hosted
    environment: production
    name: Build and Push Docker Image
    needs: checkout  # Runs after checkout
    env:
      DOCKERFILE_PATH: ${{ vars.DOCKERFILE_PATH }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      IMAGE_TAG: ${{ vars.IMAGE_TAG }}
      BASE_PATH: ${{ vars.BASE_PATH }}
      PROD_BRANCH: ${{ vars.PROD_BRANCH }}
    steps:
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Pull Latest Code
        run: |
          cd $BASE_PATH
          git pull origin $PROD_BRANCH

      - name: Pull Existing Image for Cache
        run: |
          docker pull $IMAGE_NAME:$IMAGE_TAG || true  # Pulls the image if it exists, ignores if not

      - name: Build and Push Image to GHCR with Cache
        run: |
          docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME:$IMAGE_TAG \
            --cache-from=$IMAGE_NAME:$IMAGE_TAG $BASE_PATH
          docker push $IMAGE_NAME:$IMAGE_TAG

  # Step 3: apply deployment
  Deploy:
    runs-on: self-hosted
    environment: production
    needs: build_and_push
    steps:
      - name: Deploy to Minikube
        run: |
          kubectl apply -f $DEPLOYMENT_FILE_PATH 
          kubectl apply -f $HPA_FILE_PATH
        env:
          DEPLOYMENT_FILE_PATH: ${{ vars.DEPLOYMENT_PATH }}
          HPA_FILE_PATH: ${{ vars.HPA_FILE_PATH }}


  # Step 4: Test service URLs
  Test_services:
    runs-on: self-hosted
    name: Test Service URLs
    needs: Deploy 
    steps:
    - name: Test Service URLs
      run: |
          minikube service list
          minikube service vuejs-app -n mamikos-devops --url

  # Step 5: Clean from unused docker components (images, containers)
  Cleanup:
    runs-on: self-hosted
    needs: Test_services
    steps:
    - name: Cleanup Docker
      run: |
        echo "Removing stopped containers..."
        docker container prune -f
        
        echo "Removing dangling images..."
        docker image prune -f
        
        echo "Removing unused images..."
        docker image prune -a -f
        
        echo "Cleanup completed."
